env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  # suppress errors for missing 'import React' in files
  "react/react-in-jsx-scope": "off"
  "semi": 0
  # allow jsx syntax in js files (for next.js project)
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]