env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  "linebreak-style": ["error", "windows"]
}
